// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2m6jC1K_GYkstpoL2U0ByDzWMIpBNeQY',
    appId: '1:54653675415:web:6869c4a93ff5d3260746d2',
    messagingSenderId: '54653675415',
    projectId: 'mezmuredawit-b7b19',
    authDomain: 'mezmuredawit-b7b19.firebaseapp.com',
    storageBucket: 'mezmuredawit-b7b19.firebasestorage.app',
    measurementId: 'G-0NFFN3N5S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMV4r_VoqeimKc0trxCaAi7lke4Yi5yR0',
    appId: '1:54653675415:android:819c864f072ec9a50746d2',
    messagingSenderId: '54653675415',
    projectId: 'mezmuredawit-b7b19',
    storageBucket: 'mezmuredawit-b7b19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlY0oXbI9bX06LPqwaP-O2RhgYg8_NutU',
    appId: '1:54653675415:ios:39bd20a2b5ce93820746d2',
    messagingSenderId: '54653675415',
    projectId: 'mezmuredawit-b7b19',
    storageBucket: 'mezmuredawit-b7b19.firebasestorage.app',
    iosBundleId: 'com.example.mezmureDawit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlY0oXbI9bX06LPqwaP-O2RhgYg8_NutU',
    appId: '1:54653675415:ios:39bd20a2b5ce93820746d2',
    messagingSenderId: '54653675415',
    projectId: 'mezmuredawit-b7b19',
    storageBucket: 'mezmuredawit-b7b19.firebasestorage.app',
    iosBundleId: 'com.example.mezmureDawit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2m6jC1K_GYkstpoL2U0ByDzWMIpBNeQY',
    appId: '1:54653675415:web:fad5b93e2e84b5d90746d2',
    messagingSenderId: '54653675415',
    projectId: 'mezmuredawit-b7b19',
    authDomain: 'mezmuredawit-b7b19.firebaseapp.com',
    storageBucket: 'mezmuredawit-b7b19.firebasestorage.app',
    measurementId: 'G-FYW6184XD9',
  );
}
